name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
{{#if_eq packageManagerName "pnpm"}}
      # pnpm action uses the packageManager field in package.json to
      # understand which version to install.
      - uses: pnpm/action-setup@v2
{{/if_eq}}
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: '{{ packageManagerName }}'
      - name: Install dependencies
        run: {{ packageManagerInstallCmd }}
      - name: Build plugin
        run: {{ packageManagerName }} run build
      - name: Compatibility check
        run: npx @grafana/levitate@latest is-compatible --path src/module.ts --target @grafana/data,@grafana/ui,@grafana/runtime
